### ISSUE TITLE
[Addon] A scroll bar is displayed on the Private Relay door-hanger

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#316] opened 2020-05-20 08:25 UTC
### Affected versions

Firefox 76.0.1 
Private Relay add-on version 1.4.0

### Affected platforms

Mac OS X 10.15
Windows 10 x64
Ubuntu 18.04 x64

### Steps to reproduce

1. Launch Firefox.
2. Install the Private Relay add-on.
3. In the Address Toolbar, click on the "Private Relay" button.

### Expected behavior

No scroll bar should be displayed on the Private Relay door-hanger.

### Actual behavior
A scroll bar is displayed on the Private Relay door-hanger.

![Screenshot 2020-05-20 at 09 28 53](https://user-images.githubusercontent.com/15101135/82423322-4ad82680-9a8c-11ea-8b4b-d596f41528cb.png)

**Comment by groovecoder** [comment] 2020-05-22 19:51
Marking dupe of https://github.com/mozilla/fx-private-relay/issues/315

**Closed by groovecoder** 2020-05-22 19:51 UTC
Labels: :bug: bug, duplicate, 🧩 add-on
