### ISSUE TITLE
I didn't receive the email from twitch.tv

### ISSUE THREAD

**Issue by train255** [mozilla/fx-private-relay#440] opened 2020-06-18 02:45 UTC
I tried to create an account in twitch.tv but I didn't receive the confirmation email.
![image](https://user-images.githubusercontent.com/1794649/84972102-5b8dc200-b148-11ea-81a5-168c36f37bd7.png)

**Comment by groovecoder** [comment] 2020-06-26 12:51
Thanks! We'll look into this.

**Comment by groovecoder** [comment] 2020-06-26 17:17
Twitch appears to be one of the senders triggering SNS messages with invalid signatures. Closing this as dupe of #494 . (I really hate debugging crypto code, but here we go I guess ...)

**Closed by groovecoder** 2020-06-26 17:17 UTC
Labels: :bug: bug, duplicate, ✉️ email
