### ISSUE TITLE
[Add-on] The email alias overlaps the placeholder on Google's sign in page

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/fx-private-relay#197] opened 2020-04-24 07:01 UTC
**Affected versions**
* latest Nightly 77.0a1

**Affected platforms**
* Windows 10 x64
* macOS 10.15
* Ubuntu 18.04 x64

**Prerequisites**
* Firefox is opened.
* Have the Private Relay add-on version 1.2.0 installed - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view.

**Steps to reproduce**
1. Access https://accounts.google.com/signin.
2. Create an email alias using the Private relay icon or via context menu.
3. Inspect the generated email alias.

**Expected result**
* The email alias is correctly displayed in the email field.

**Actual result**
* The alias overlaps the placeholder inside the email field.

**Additional notes**
* please observe the attached screenshot
![Screenshot from 2020-04-24 09-52-46](https://user-images.githubusercontent.com/43886441/80183817-3120fc00-8612-11ea-8c08-640796a45c6d.png)

**Comment by sandysage** [comment] 2020-05-04 01:17
While we don't want to prioritize specific site compatibility issues just yet, this seems like a pretty commonly seen case. Marking as P2 to see where this fits in with the next release.

**Comment by groovecoder** [comment] 2020-07-22 16:01
Can't reproduce this anymore. Closing.

**Closed by groovecoder** 2020-07-22 16:01 UTC
Labels: :bug: bug, priority-P2, website compat bug, 🧩 add-on
