### ISSUE TITLE
[Button] Email placeholder is not displayed

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#332] opened 2020-05-21 11:52 UTC
### Affected versions

Nightly 77.0a1
Private Relay add-on version 1.4.0

### Affected platforms

Windows 10 and 7 x64
Mac OS X 10.14
Ubuntu 18.04

### Steps to reproduce

1. Launch the latest Nightly
2. Install the Private Relay add-on and sign in
3. Go to Netflix.com and observe the email field (also reproducible on Apple.com / walmart.com / dropbox.com)

### Expected behavior

Email placeholder should be displayed on netflix.com

### Actual behavior

Email placeholder is not displayed on netflix.com
![Screenshot 2020-05-21 at 14 51 51](https://user-images.githubusercontent.com/15101135/82556552-a250c200-9b72-11ea-8320-458e1836ba2e.png)
![2020-05-22_14h21_53](https://user-images.githubusercontent.com/15101135/82663465-66803000-9c38-11ea-91ad-42ea5e87dad2.png)

### Note

Private relay button is not correctly aligned

**Comment by groovecoder** [comment] 2020-05-26 17:18
Ah, this is a dupe of #212 on another site.

**Closed by groovecoder** 2020-05-26 17:18 UTC
Labels: :bug: bug, duplicate, website compat bug
