### ISSUE TITLE
[Adobe] E-mail field with generated alias gets cleared out upon typing in other fields from the Register form

### ISSUE THREAD

**Issue by TimeaC** [mozilla/fx-private-relay#340] opened 2020-05-22 12:29 UTC
**Affected Version**
Release Version 76.0.1 (64-bit)
Private Relay Add-on version 1.4.0

**Tested on**
Windows 10 x64

**Steps to reproduce:**

1. Launch latest Firefox Release
2. Install Private Relay add-on and log in
3. Go to Adobe Register form
4. Generate an alias for the email field
4. Select a different field and start typing into it 

**Expected:**
The field should remain filled and the sign-up process should continue.

**Actual:**
The field was cleared out.
Video: https://streamable.com/qeig6v

**Comment by groovecoder** [comment] 2020-05-26 17:07
Another dupe of #331

**Closed by groovecoder** 2020-05-26 17:07 UTC
Labels: :bug: bug, duplicate, website compat bug, 🧩 add-on
