### ISSUE TITLE
[Website] [Extension] Website doesn't update, even after refresh, if you enable the extension during a session

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/fx-private-relay#506] opened 2020-06-25 18:34 UTC
I had the Private Relay extension disabled. 

I enabled it. I refreshed the Private Relay website. It still showed the message saying that I didn't have the extension (even though I do!) I haven't restarted the browser yet or signed out, then sign back in, but I'm wondering if this can update more immediately, perhaps after a refresh of the page (without requiring signing out/restarting)? 

Screenshot that shows the message you get on the website when it thinks you don't have the extension yet:
![Screen Shot 2020-06-25 at 11 10 51 AM](https://user-images.githubusercontent.com/911251/85778802-cf474600-b6d7-11ea-9624-9ce7a6f07091.png)

**Comment by groovecoder** [comment] 2020-06-26 12:41
Closing as dupe of #486

**Closed by groovecoder** 2020-06-26 12:41 UTC
Labels: duplicate
