### ISSUE TITLE
[DropBox] E-mail field with generated alias is cleared out upon clicking on required check-boxes on the Register form 

### ISSUE THREAD

**Issue by TimeaC** [mozilla/fx-private-relay#339] opened 2020-05-22 11:58 UTC
**Affected Version**
Release Version 76.0.1 (64-bit)
Private Relay Add-on version 1.4.0

**Tested on**
Windows 10 x64

**Steps to reproduce:**

1. Launch latest Firefox Release
2. Install Private Relay add-on and log in
3. Go to dropbox Register form
4. Generate an alias for the email field
4. Check any of the 2 checkboxes on the form

**Expected:**
The field should remain filled and the sign-up process should continue.

**Actual:**
The field was cleared out. 
Video: https://streamable.com/abctmi

**Comment by sbadau** [comment] 2020-05-25 13:13
I can also reproduce this issue on Linkedin - as soon as I check the Agree & Join button, the email and the passwords fields are cleared (used Firefox 76.0.1 and Private Relay 1.4.0). Please see the screencast.

![linkedin](https://user-images.githubusercontent.com/56026823/82815790-8f0b6280-9ea2-11ea-8f28-ce165bb7f89a.gif)

**Comment by groovecoder** [comment] 2020-05-26 17:07
Going to close this as a duplicate of #331 - good to know the other sites where this happens, but let's keep a single bug for "input is cleared out"

**Closed by groovecoder** 2020-05-26 17:07 UTC
Labels: :bug: bug, duplicate, website compat bug, 🧩 add-on
