### ISSUE TITLE
Choosing the destination email

### ISSUE THREAD

**Issue by kam193** [mozilla/fx-private-relay#1542] opened 2022-02-14 15:59 UTC
Hi,
looks like Relay is forcing me to forward emails to the Firefox Account's main address. Are here any plans to allow choosing another email (either just another, or e.g. one of alternate Fx Account's emails)?

**Comment by tcinotto** [comment] 2022-02-14 22:34
Hi @kam193 thank you for the feature request. This is currently in our backlog, and we can hope to provide updates in the future.

**Comment by groovecoder** [comment] 2022-02-15 19:26
Closing as dupe of https://github.com/mozilla/fx-private-relay/issues/564. (Upvote there please)

**Closed by groovecoder** 2022-02-15 19:26 UTC
