### ISSUE TITLE
E-mail field overlaps the captcha window on some sites Log In form if private relay is installed

### ISSUE THREAD

**Issue by TimeaC** [mozilla/fx-private-relay#330] opened 2020-05-21 11:00 UTC
**Affected Version**
Release Version 76.0.1 (64-bit)
Private Relay Add-on version 1.4.0

**Affected sites:**
1. Zoom
2. StackOverflow
3. Spotify
4. Yelp.ie
5. Indeed.com

**Tested on**
Windows 10 x64
Ubuntu 18.04

**Steps to reproduce:**

1. Launch latest Firefox Release
2. Install Private Relay add-on and log in
3. Go to zoom.com and create an account using private relay mail
4. Log out and reach the Log In form
5. Fill in the alias mail and password and Log In

**Expected:**
The captcha with images should be displayed correctly.

**Actual:**
The e-mail field overlaps the image captcha window if private relay addon is installed
![2020-05-21_13h36_01](https://user-images.githubusercontent.com/65650857/82552723-564e4f00-9b6b-11ea-9a5f-18818e90b405.png) 
![StackOverflow](https://user-images.githubusercontent.com/65650857/82652255-fcf72600-9c25-11ea-8a20-addcbd12fcfd.png)

**Comment by sbadau** [comment] 2020-05-25 08:30
Email field overlaps also when the Solutions drop-down when it's toggled on Zoom.  Please see the screencast for more details.

![ZoomDropDown](https://user-images.githubusercontent.com/56026823/82794460-2f4d9100-9e7b-11ea-822e-df842bc003a1.gif)

**Comment by sbadau** [comment] 2020-05-25 14:13
Reproduced this issue also on indeed.com - used Fx 76.0.1 and Private Relay 1.4.0

![indeed](https://user-images.githubusercontent.com/56026823/82820507-fdecb980-9eaa-11ea-8f91-7ca4f6b6000d.gif)

**Comment by sbadau** [comment] 2020-07-01 15:08
This issue is also reproducible with the latest version of the Private Relay add-on (1.4.1, updated on June 26, 2020) and Firefox 77.0.1. 
Reproduced it on:
- zoom.us
- Yelp.ie
- Indeed.com

For an unknown reason, I didn't get the captcha window on Spotify and StackOverflow, so I couldn't reproduce it the

**Comment by groovecoder** [comment] 2020-07-22 15:59
This bug appears to be a dupe of the underlying issue: https://github.com/mozilla/fx-private-relay/issues/245

**Closed by groovecoder** 2020-07-22 15:59 UTC
Labels: :bug: bug, duplicate, priority-P2, website compat bug, 🧩 add-on
