### ISSUE TITLE
[Addon] Links color is changed on some websites when Private Relay add-on is installed

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#341] opened 2020-05-22 12:34 UTC
**Affected versions**
Firefox 76.0.1
Private Relay add-on version 1.4.0 

**Affected platforms**
Windows 10
Mac OS X 10.14
Ubuntu 18.04

**Steps to reproduce**:
1. Launch Firefox.
2. Install the Private Relay add-on
3. Navigate to https://www.dropbox.com/ and Sign Up
4. Observe the color of the links from the Signup form

**Expected behavior**
The color of the links should be blue.

**Actual behavior**
The color of the links is black.

Reproduced this issue on the following websites: 
https://www.dropbox.com/
https://www.google.com/

Please see the screenshots for more details: 
![dropboxlinks](https://user-images.githubusercontent.com/56026823/82667963-810ad700-9c41-11ea-998a-d7b09fed9d98.png)

![2020-05-22_15h31_21](https://user-images.githubusercontent.com/56026823/82667977-86682180-9c41-11ea-99f2-e8970f93733f.png)

**Comment by ExE-Boss** [comment] 2020-06-23 14:17
Duplicate of <https://github.com/mozilla/fx-private-relay/issues/472>

**Comment by dgdavid** [comment] 2020-06-23 14:26
> Duplicate of #472

Actually, #472 is somehow a duplicated of this. Or just a more technical report. But this issue was reported ~ 1 month ago.

**Comment by jens1o** [comment] 2020-06-23 17:24
Since the last few days, this affects me on more and more websites. What is the current priority for this?

Also, I noticed that headings get their `font-weight` reset to `normal`?

**Comment by cadeyrn** [comment] 2020-06-23 17:34
I was just about to open a ticket about this one. I notices a color change in WordPress, too, but much more critical: the add-on changes the font rendering on almost every website.

**Comment by groovecoder** [comment] 2020-06-25 18:38
Closing this now that #501 is merged. All sites should be fixed in next release.

**Closed by groovecoder** 2020-06-25 18:38 UTC
Labels: website compat bug, 🧩 add-on
