### ISSUE TITLE
Add more than one forwarding address

### ISSUE THREAD

**Issue by imcardle** [mozilla/fx-private-relay#2967] opened 2023-01-03 19:23 UTC
I would like to be able to forward messages to more than one of my real email addresses.

**Comment by Vinnl** [comment] 2023-01-04 10:40
Thanks for reporting this @imcardle. I think this is a duplicate of https://github.com/mozilla/fx-private-relay/issues/564, so please upvote/subscribe to that issue instead.

**Closed by Vinnl** 2023-01-04 10:40 UTC
