### ISSUE TITLE
[Patch.com] E-mail field with generated alias overflows the Zip code search dropdown

### ISSUE THREAD

**Issue by TimeaC** [mozilla/fx-private-relay#342] opened 2020-05-22 12:46 UTC
**Affected Version**
Release Version 76.0.1 (64-bit)
Private Relay Add-on version 1.4.0

**Tested on**
Windows 10 x64
Ubuntu 18.04
MacOS 10.15

**Steps to reproduce:**

1. Launch latest Firefox Release
2. Install Private Relay add-on and log in
3. Go to Patch.com and generate an alias for the mail field
4. Search for any zip code and check the dropdown

**Expected:**
The search dropdown should be correctly displayed.

**Actual:**
The e-mail field overflows the zip code search dropdown. Video: https://streamable.com/n9b9sj

**Comment by groovecoder** [comment] 2020-05-26 17:09
Going to call this a dupe of #330 - we'll use that as a single issue to track site compat bugs where the email input over[laps/flows/lays] other form elements.

**Closed by groovecoder** 2020-05-26 17:09 UTC
Labels: :bug: bug, duplicate, website compat bug, 🧩 add-on
