### ISSUE TITLE
[feedback] choose which email address to forward emails to if you have any secondary addresses in your account

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#675] opened 2020-09-14 19:42 UTC
name: Uuuui
score: 4 ✯ ✯ ✯ ✯
created: 2020-09-03
url: https://addons.mozilla.org/firefox/addon/private-relay/reviews/1591933

> I like this extension, but it could be a bit better if you could **choose which email address to forward emails to if you have any secondary addresses in your account.**
> Better yet, there could be the option to manually type the email address in, allowing you to choose whichever one you want. However, I understand if the developers don't want to add that feature because of the risk for abuse.
> Also, if there is a way for Mozilla/Firefox Relay to tell me when a message that was supposed to be forwarded was blocked because it was too large, I'd like this extension/service even more.  I'm happy with how this extension is currently, but I still think it has some room for improvements.

**Comment by groovecoder** [comment] 2020-09-21 17:47
Duplicate of https://github.com/mozilla/fx-private-relay/issues/564

**Closed by groovecoder** 2020-09-21 17:47 UTC
Labels: addon-review, duplicate
