### ISSUE TITLE
Show the sender's email address

### ISSUE THREAD

**Issue by geckonapper** [mozilla/fx-private-relay#3796] opened 2023-08-17 15:21 UTC
Sometimes it would be desirable to send a message to the sender directly, outside of Relay.  However, there's no way to do that because you don't display the the senders email address.  Please display the sender's email address, or better yet, display the message source.

**Comment by Vinnl** [comment] 2023-08-18 12:35
@geckonapper Is the sender's email address not visible in the name field for you? For example, I see this:

![Email sender: "info@fluffdisco.nl [via Relay]" <replies@relay.firefox.com>](https://github.com/mozilla/fx-private-relay/assets/4251/c3c0f071-2679-4805-ba8f-b25a3ca8f31a)

**Comment by groovecoder** [comment] 2023-08-18 14:23
Closing because we can't reproduce. Please re-open if you can show an email with more details: where is the sender's address missing?

**Closed by groovecoder** 2023-08-18 14:23 UTC
