### ISSUE TITLE
Can't sing up with aliases generated via context menu or button

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#629] opened 2020-08-14 08:30 UTC
**Affected versions**
Firefox 79
Firefox Private Relay 1.4.4 (used the AMO version because of the characters number limitation when creating accounts)

**Affected platforms**
Ubuntu 18.04
Mac OS X 10.5
Windows 10

**Steps to reproduce**:
1. Launch Firefox.
2. Install the Firefox Private Relay add-on and SIgn in
3. Navigate to Microsoft.com, reach the sign-up form
5. Create a new account using a generated alias via context menu or by clicking on the "Generate new alias" button from the email field.

**Expected behavior**
A new account should be created.

**Actual behavior**
I get an error stating that  "An email address is required". If I generate an account in the Firefox Relay Website, copy and paste it in the email field, then I can create the new account.
Please see the screencast for more details.

**Affected websites**
https://www.bing.com
https://www.apple.com/

![2020-08-14_11h13_00](https://user-images.githubusercontent.com/56026823/90229892-53d55b80-de21-11ea-8cef-0bd47efecf03.gif)

**Comment by birdsarah** [comment] 2020-10-26 17:44
Dupe of #350

**Closed by birdsarah** 2020-10-26 17:45 UTC
Labels: :bug: bug, website compat bug, 🧩 addon
