### ISSUE TITLE
[feedback] Add the ability to choose the address to forward the emails to

### ISSUE THREAD

**Issue by LegitBaboulinet** [mozilla/fx-private-relay#656] opened 2020-08-27 09:52 UTC
Emails seem to be forwarded to the primary email address of the firefox account.
I manage my own email server with my own domain name. I would really appreciate to be able to forward emails to forward@mydomainname for instance.

**Comment by groovecoder** [comment] 2020-08-31 19:15
Thanks for the issue. This is a dupe of #564. Can you upvote and/or comment there?

**Closed by groovecoder** 2020-08-31 19:15 UTC
Labels: duplicate
