### ISSUE TITLE
[Button] Email field is over lapping verify email/phone popups

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#430] opened 2020-06-17 12:55 UTC
### Affected versions

Firefox 76.0.1
Firefox Private Relay 1.3.1

### Affected platforms

Windows 10
Mac OS X 10.14
Ubuntu 18.04

### Steps to reproduce:

1. Launch Firefox.
2. Install the Private Relay add-on.
3. Go to https://appleid.apple.com/account#!&page=create and start creating an account.

### Expected behavior

verify email/phone popups should be correctly displayed.

### Actual behavior

Email field is over lapping verify email/phone popups.
![Screenshot 2020-06-17 at 15 27 44](https://user-images.githubusercontent.com/15101135/84900553-f20fa400-b0b2-11ea-9164-97ea64cb5698.png)

**Comment by groovecoder** [comment] 2020-07-22 15:58
This bug appears to be a dupe of the underlying issue: https://github.com/mozilla/fx-private-relay/issues/245

**Closed by groovecoder** 2020-07-22 15:58 UTC
Labels: :bug: bug, duplicate, website compat bug, 🧩 add-on
