### ISSUE TITLE
Sign out from https://relay.firefox.com/accounts/profile/ didn't actually signed user out.

### ISSUE THREAD

**Issue by alqomar** [mozilla/fx-private-relay#3798] opened 2023-08-18 03:29 UTC
I'm not sure where to report this, bugzilla/here. Sorry if this is the wrong place.

Steps to reproduce:
1. Open https://relay.firefox.com/ .
2. Sign in.
3. Sign in success, redirect to https://relay.firefox.com/accounts/profile/ .
4. Sign out.
5. Sign out success. Confirmed with "You have signed out." message.
However,
6. Sign in again from https://relay.firefox.com/ or https://accounts.firefox.com/
7. No email / password question, just click Sign In button.
8. Sign in success.

This only happen in https://relay.firefox.com. 
Sign in/out from https://account.firefox.com, work as expected.

**Comment by alqomar** [comment] 2023-08-18 06:24
Actually https://account.firefox.com also affected .

Steps to reproduce:

1. Open https://account.firefox.com .
2. Sign in.
3. Sign out.
4. Open https://relay.firefox.com .
5. Automatically signed in & redirected to https://relay.firefox.com/accounts/profile/ .

**Comment by groovecoder** [comment] 2023-08-18 14:21
>7. No email / password question, just click Sign In button.

This is expected. When you sign out of relay.firefox.com, you DO NOT automatically sign out of accounts.firefox.com. So, since you have an active signed-in session with accounts.firefox.com, you do not need to re-enter your password. You only need to click "Sign in" to sign into Relay.

> 5. Automatically signed in & redirected to https://relay.firefox.com/accounts/profile/ .

I wasn't able to reproduce this. I did this:
1. Sign out of relay.firefox.com
2. Sign out of accounts.firefix.com
3. Open relay.firefox.com
4. Click Sign in
   * I was prompted for email and password on accounts.firefox.com

Try the above steps? If it works, then everything is working as expected.

**Comment by groovecoder** [comment] 2023-08-18 14:22
Closing because I can't reproduce an error scenario.

**Closed by groovecoder** 2023-08-18 14:22 UTC
