### ISSUE TITLE
Colors issue for the AMO reviews section from the Relay Home page

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#2097] opened 2022-06-20 08:23 UTC
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Do NOT be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay Home page and scroll down to the AMO reviews section;
2. Observe the stars above the rating;
3. Observe the stars and the quotation marks above the review displayed;

#### Expected result:
- The stars should be yellow/golden, and the quotation marks should be purple;

#### Actual result:
- All the stars and quotation marks that are initially displayed are black;

#### Notes:
- Moving to a different review switches the stars and quotation marks related to the review to the right colors, including for the initial review, but not for the add-on rating;
- See attached media:
Stage:
![image](https://user-images.githubusercontent.com/85748693/174557108-2273643b-474c-4c17-9de4-3901931e9e84.png)
Figma reference:
![image](https://user-images.githubusercontent.com/85748693/174557174-73be527e-d3f1-4f7b-9e7f-6a93ff301b44.png)
Stage gif:
![color](https://user-images.githubusercontent.com/85748693/174557274-33594aa8-c96c-4007-a591-aec6f897de85.gif)

**Comment by Vinnl** [comment] 2022-06-21 13:50
Closing this as a duplicate of #2063, as the fix is the same (https://github.com/mozilla/fx-private-relay/pull/2105).

**Closed by Vinnl** 2022-06-21 13:51 UTC
Labels: :bug: bug
