### ISSUE TITLE
Encoding bug in from: field

### ISSUE THREAD

**Issue by winkler-winsen** [mozilla/fx-private-relay#645] opened 2020-08-24 09:29 UTC
Should look like this:
![image](https://user-images.githubusercontent.com/43114182/91027881-f4373700-e5fc-11ea-88c4-348e60e029ed.png)
`From:  =?UTF-8?Q?D=C3=84NISCHES=20BETTENLAGER?= <info@news.daenischesbettenlager.de>`

But it looks like this:
![image](https://user-images.githubusercontent.com/43114182/91027788-cce06a00-e5fc-11ea-9371-36e3c40d1ab2.png)
`From: "\"D�½NISCHES BETTENLAGER\" <info@news.daenischesbettenlager.de> [via Relay]" `

**Comment by groovecoder** [comment] 2020-08-24 19:17
Duplicate of #523

**Closed by groovecoder** 2020-08-24 19:17 UTC
Labels: :bug: bug, duplicate, ✉️ email
