### ISSUE TITLE
"Real email" is used instead of "true email"

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#2190] opened 2022-07-13 07:37 UTC
**Build:**
Production

**Affected platforms:**
Windows 10

**Browsers tested on:**
Firefox, latest release
Chrome, latest release

**Preconditions:**
N/A

**Steps to reproduce:**
1. Go to Relay page.
2. Scroll to the Use cases section and observe the text for the following cases: Shopping, On the go and Signups.

**Actual result:**
"real email" is used instead of true email.

**Expected result:**
"true email" is used.

**Notes:**
N/A
![real email instead of true email](https://user-images.githubusercontent.com/79697848/178677380-1ddb5816-a00a-414f-aa17-29589aac1a95.PNG)

![real email instead of true 1](https://user-images.githubusercontent.com/79697848/178677387-7f19a65a-1765-4682-b315-5200c8fa9485.PNG)

![real email instead of true 2](https://user-images.githubusercontent.com/79697848/178677407-e16654fc-f343-4472-a614-0e8527d0c2ca.PNG)

**Comment by joaonunomota** [comment] 2023-04-21 11:27
https://github.com/mozilla/fx-private-relay/pull/3075 removed use cases from the home page, so I think this issue can be closed.

It is also a duplicate of https://github.com/mozilla/fx-private-relay/issues/1952, but this issue has more details.

**Comment by jwhitlock** [comment] 2023-04-21 14:10
Thanks @joaonunomota, I agree this can be closed.

**Closed by jwhitlock** 2023-04-21 14:10 UTC
