### ISSUE TITLE
'Private Relay' extension overrides link colors on other webpages

### ISSUE THREAD

**Issue by donmccurdy** [mozilla/fx-private-relay#490] opened 2020-06-24 16:50 UTC
When the 'Private Relay' extension is enabled, links are no longer shown in an accent color on various websites. Here's a screenshot from GitHub, with and without the extension:

| Private Relay enabled | Private Relay disabled |
|---|---|
| ![Screen Shot 2020-06-24 at 9 48 32 AM](https://user-images.githubusercontent.com/1848368/85598029-0b0edc80-b600-11ea-9d10-a02313619b44.png) | ![Screen Shot 2020-06-24 at 9 48 40 AM](https://user-images.githubusercontent.com/1848368/85598037-0c400980-b600-11ea-809f-98f9f46e28b7.png) |

**Comment by groovecoder** [comment] 2020-06-24 18:32
Thanks for the bug report. Marking as dupe of https://github.com/mozilla/fx-private-relay/issues/472

**Closed by groovecoder** 2020-06-24 18:32 UTC
Labels: duplicate
