### ISSUE TITLE
Select email alias from addon button

### ISSUE THREAD

**Issue by CarmeloPatti** [mozilla/fx-private-relay#726] opened 2020-10-30 09:14 UTC
Hallo all and thanks for this fantastic extension!

What about allowing do select an already defined alias directly from here?

![image](https://user-images.githubusercontent.com/63046420/97683281-a88b8880-1a98-11eb-92f5-129cbe0d61f5.png)

Thanks!

**Comment by groovecoder** [comment] 2020-11-02 18:37
Thanks for the feedback. I'm closing this as a dupe of https://github.com/mozilla/fx-private-relay/issues/661 where we have captured lots of ideas for improving the pop-up.

**Closed by groovecoder** 2020-11-02 18:37 UTC
Labels: duplicate

**Comment by tootee44** [comment] 2020-12-31 22:00
#736
