### ISSUE TITLE
Mobile: The “Create a new custom alias” modal is displayed bigger than the phone screen

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1528] opened 2022-02-10 14:09 UTC
#### Build:
- Stage;

#### Affected Platforms:
- Android 11;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a least one alias created;
- Have a Custom Domain Name set;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the “Generate New Alias” button;
3. In the opened drop-down menu, click on the “@<Custom Domain Name>” option;
4. Observe the results;

#### Expected result:
- The “Create a new custom alias” modal opens without any display or layout issues;

#### Actual result:
- The opened modal is displayed bigger than the phone’s screen;

#### Notes:
- This might be related to the fact that the Custom Domain Names seem to go out of the phone’s screen as well, as on Stage they also contain “.fxprivaterelay.nonprod.cloudops.mozgcp.net”;
- See attached media:
https://user-images.githubusercontent.com/85748693/153424293-37a96535-c516-4151-9236-503fd7649c8c.mp4

**Comment by Vinnl** [comment] 2022-04-25 11:23
I think #1612 is a duplicate of this (but with an embedded video, so I'll close this one).

**Closed by Vinnl** 2022-04-25 11:23 UTC
