### ISSUE TITLE
I can't copy the email alias more than once

### ISSUE THREAD

**Issue by ajr-dev** [mozilla/fx-private-relay#740] opened 2020-11-26 14:31 UTC
In [this page](https://relay.firefox.com/accounts/profile/) it only allows me to copy the email once. I need to copy it more than once.

**Comment by groovecoder** [comment] 2020-11-30 18:38
Calling this a dupe of #445. Please upvote and comment there.

**Closed by groovecoder** 2020-11-30 18:38 UTC
Labels: duplicate
