### ISSUE TITLE
[Website] Can't uncheck "Forward emails to" box

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#329] opened 2020-05-21 09:39 UTC
**Affected versions**
Firefox 76.0.1
Private Relay add-on version 1.4.0 

**Affected platforms**
Windows 10
Mac OS X 10.14
Ubuntu 18.04

**Steps to reproduce**:
1. Launch Firefox.
2. Sign in to https://relay.firefox.com/
3. Install the Private Relay add-on
4. In the address bar, click on the Private relay add-on and copy one alias
5. Paste the copied alias into the address bar and click enter
6. Uncheck the box for the "Forward emails to" option.

**Expected behavior**
The "Forward emails to" box should be properly unchecked.

**Actual behavior**
The "Forward emails to" box can't be unchecked if the private relay website is opened by copy-pasting the alias into the address bar.

Please see the screencast for more details
![uncheck](https://user-images.githubusercontent.com/56026823/82545984-15047200-9b60-11ea-8c05-cf505a5c81c8.gif)

**Comment by groovecoder** [comment] 2020-05-26 19:07
Whoa, nice find. Caused by this JS error in app.js:
```
Uncaught (in promise) TypeError: Window.fetch: https://qmxt0c5up@relay.firefox.com/emails/ is an url with embedded credentials.
```

**Comment by groovecoder** [comment] 2020-07-22 15:51
Should be fixed in latest.

**Closed by groovecoder** 2020-07-22 15:51 UTC
Labels: :bug: bug, 🕸 website
