### ISSUE TITLE
[Button] The Private Relay button is not displayed on the popup Sign-up forms

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#205] opened 2020-04-24 13:31 UTC
### Affected versions

* Nightly 77.0a1
* Private Relay add-on version 1.2.0 - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view

### Affected platforms

* Windows 10 and 7 x64
* Mac OS X 10.14
* Ubuntu 18.04

### Steps to reproduce

1. Launch the latest Nightly.
2. Install the Private Relay add-on and sign in.
3. Go to any website with a popup sign up form (ex. reddit.com / twitter.com / aliexpress.com / https://www.etsy.com/)

### Expected behavior

The Private Relay button should be displayed on the popup Sign-up forms.

### Actual behavior

The Private Relay button is not displayed on the popup Sign-up forms.
![Screenshot 2020-04-24 at 16 29 40](https://user-images.githubusercontent.com/15101135/80217791-f6868600-8648-11ea-914e-58534da66695.png)

### Note

The button is displayed if you open the sign up form in a new tab.

**Comment by groovecoder** [comment] 2020-05-26 17:27
Dupe of #203. Will use that issue to track sites where the button is missing.

**Closed by groovecoder** 2020-05-26 17:27 UTC
Labels: :bug: bug, duplicate, website compat bug, 🧩 add-on
