### ISSUE TITLE
[Website] "Looks like you haven't installed the add-on... yet!" message is displayed even if the add-on is installed

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#508] opened 2020-06-26 12:18 UTC
### Affected versions

Firefox 76.0.1
Firefox Private Relay 1.4.1

### Affected platforms

Windows 10
Mac OS X 10.14
Ubuntu 18.04

### Steps to reproduce:

1. Launch Firefox.
2. Install the Private Relay add-on.
3. Click on the addon and then on "Continue" and login into your private relay account.

### Expected behavior
No message should be displayed to install the add-on when the add-on is already installed.

### Actual behavior
"Looks like you haven't installed the add-on... yet!" message is displayed even if the add-on is installed

![Screenshot 2020-06-26 at 14 03 44](https://user-images.githubusercontent.com/15101135/85856025-e19caf00-b7bf-11ea-9b93-2ca13a6f1c78.png)

**Comment by sv-hyacoub** [comment] 2020-06-26 12:19
This issue might be related to issue #505 and #506.

**Comment by groovecoder** [comment] 2020-06-26 12:41
Closing as dupe of #486

**Closed by groovecoder** 2020-06-26 12:41 UTC
Labels: duplicate
