### ISSUE TITLE
[feedback] Forwarded email contains a bunch of \ufffd Unicode replacement characters

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#653] opened 2020-08-26 20:42 UTC
via https://addons.mozilla.org/en-US/firefox/addon/private-relay/reviews/1585861/

Original: 

> По этой ссылке скриншот того, как пришло письмо после прогона через Релэй , не спам и не вирусы https://prnt.sc/u3hpb7

Translation:

> Following this link is a screenshot of how the letter came after running through Relay, not spam or viruses https://prnt.sc/u3hpb7

![Banners_and_Alerts_and_Screenshot_by_Lightshot](https://user-images.githubusercontent.com/557895/91354550-c17a7380-e7a1-11ea-82a7-6d0357e1ecf1.png)

**Comment by pdehaan** [comment] 2020-08-26 20:43
This was the unicode issue w/ discussed in the last triage meeting.
https://www.fileformat.info/info/unicode/char/fffd/index.htm

Just wanted to make sure this was captured somewhere. <3

**Comment by groovecoder** [comment] 2020-08-31 19:09
Dupe of https://github.com/mozilla/fx-private-relay/issues/655

**Closed by groovecoder** 2020-08-31 19:09 UTC
Labels: duplicate
