### ISSUE TITLE
Can't delete my alias after clicking on 'delete' button

### ISSUE THREAD

**Issue by brassy-** [mozilla/fx-private-relay#237] opened 2020-04-29 14:26 UTC
When I try to delete my alias, after clicking on delete, I'm not able to:
- delete my alias
- close the panel

![image](https://user-images.githubusercontent.com/6309827/80607321-a71fcb80-8a35-11ea-8d1e-5cc2a03be494.png)

I attach a [video](https://github.com/mozilla/fx-private-relay/files/4552213/delete-panel-fx-relay.mov.zip) showing the behaviour.

**Comment by groovecoder** [comment] 2020-05-01 15:50
Thanks for the bug report. Are you running any other add-ons that might be disabling some of the Javascript?

**Comment by groovecoder** [comment] 2020-05-04 21:06
I was unable to reproduce this. Maybe @sbadau and/or @GeorgiuCiprian can help us come up with steps to reproduce?

**Comment by sbadau** [comment] 2020-05-05 11:24
I couldn't reproduce it either, tried on several Firefox versions - Nightly 78.0a1, Firefox 77 beta 1, Firefox 75 and several operating systems - Windows 10 x64, Ubuntu 18.05, Mac Os X 10.14  and Mac Os X 10.13 (iMac 21.5-inch) and Mac OS X 10.15 (MacBook Pro Retina - 15-inch).

**Comment by groovecoder** [comment] 2020-05-05 16:31
Okay, I'm going to close this then. @brassy- can you try again? You may have been using the dashboard when we had an error that's been fixed since then?

**Closed by groovecoder** 2020-05-05 16:31 UTC
Labels: :bug: bug, priority-P1, 🕸 website

**Comment by groovecoder** [comment] 2020-05-11 16:00
This fix has been deployed to the production site now. Should be working for you. Please try again?
